# Generated by Django 4.2.23 on 2025-10-24 07:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sril', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='archivo_pdf',
            field=models.FileField(blank=True, help_text='Subir archivo PDF del libro', null=True, upload_to='libros/pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='libro',
            name='disponible_descarga',
            field=models.BooleanField(default=False, help_text='¿Está disponible para descarga?'),
        ),
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, help_text='Portada generada automáticamente desde el PDF', null=True, upload_to='libros/portadas/'),
        ),
    ]
