# Generated by Django 4.2.23 on 2025-10-24 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sril', '0002_libro_archivo_pdf_libro_disponible_descarga_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='libro',
            name='sril_libro_titulo_751fe7_idx',
        ),
        migrations.RemoveIndex(
            model_name='libro',
            name='sril_libro_autor_e53e3d_idx',
        ),
    ]
